package com.pangge.moontest;

import org.greenrobot.greendao.annotation.*;
import org.simpleframework.xml.Attribute;
import org.simpleframework.xml.Root;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CITY".
 */

@Root(name = "d", strict = false)
@Entity
public class City {

    @Id
    private Long id;

    @NotNull
    @Attribute(name = "d1",required = false)
    private String d1;

    @NotNull
    @Attribute(name = "d2",required = false)

    private String d2;

    @NotNull
    @Attribute(name = "d3",required = false)

    private String d3;

    @NotNull
    @Attribute(name = "d4",required = false)

    private String d4;

    @Generated
    public City() {
    }

    public City(Long id) {
        this.id = id;
    }

    @Generated
    public City(Long id, String d1, String d2, String d3, String d4) {
        this.id = id;
        this.d1 = d1;
        this.d2 = d2;
        this.d3 = d3;
        this.d4 = d4;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getD1() {
        return d1;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setD1(@NotNull String d1) {
        this.d1 = d1;
    }

    @NotNull
    public String getD2() {
        return d2;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setD2(@NotNull String d2) {
        this.d2 = d2;
    }

    @NotNull
    public String getD3() {
        return d3;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setD3(@NotNull String d3) {
        this.d3 = d3;
    }

    @NotNull
    public String getD4() {
        return d4;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setD4(@NotNull String d4) {
        this.d4 = d4;
    }

}
