package com.pangge.moontest;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.pangge.moontest.Weather1;
import com.pangge.moontest.Weather2;
import com.pangge.moontest.Weather3;
import com.pangge.moontest.Weather4;
import com.pangge.moontest.Weather5;
import com.pangge.moontest.City;

import com.pangge.moontest.Weather1Dao;
import com.pangge.moontest.Weather2Dao;
import com.pangge.moontest.Weather3Dao;
import com.pangge.moontest.Weather4Dao;
import com.pangge.moontest.Weather5Dao;
import com.pangge.moontest.CityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig weather1DaoConfig;
    private final DaoConfig weather2DaoConfig;
    private final DaoConfig weather3DaoConfig;
    private final DaoConfig weather4DaoConfig;
    private final DaoConfig weather5DaoConfig;
    private final DaoConfig cityDaoConfig;

    private final Weather1Dao weather1Dao;
    private final Weather2Dao weather2Dao;
    private final Weather3Dao weather3Dao;
    private final Weather4Dao weather4Dao;
    private final Weather5Dao weather5Dao;
    private final CityDao cityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        weather1DaoConfig = daoConfigMap.get(Weather1Dao.class).clone();
        weather1DaoConfig.initIdentityScope(type);

        weather2DaoConfig = daoConfigMap.get(Weather2Dao.class).clone();
        weather2DaoConfig.initIdentityScope(type);

        weather3DaoConfig = daoConfigMap.get(Weather3Dao.class).clone();
        weather3DaoConfig.initIdentityScope(type);

        weather4DaoConfig = daoConfigMap.get(Weather4Dao.class).clone();
        weather4DaoConfig.initIdentityScope(type);

        weather5DaoConfig = daoConfigMap.get(Weather5Dao.class).clone();
        weather5DaoConfig.initIdentityScope(type);

        cityDaoConfig = daoConfigMap.get(CityDao.class).clone();
        cityDaoConfig.initIdentityScope(type);

        weather1Dao = new Weather1Dao(weather1DaoConfig, this);
        weather2Dao = new Weather2Dao(weather2DaoConfig, this);
        weather3Dao = new Weather3Dao(weather3DaoConfig, this);
        weather4Dao = new Weather4Dao(weather4DaoConfig, this);
        weather5Dao = new Weather5Dao(weather5DaoConfig, this);
        cityDao = new CityDao(cityDaoConfig, this);

        registerDao(Weather1.class, weather1Dao);
        registerDao(Weather2.class, weather2Dao);
        registerDao(Weather3.class, weather3Dao);
        registerDao(Weather4.class, weather4Dao);
        registerDao(Weather5.class, weather5Dao);
        registerDao(City.class, cityDao);
    }
    
    public void clear() {
        weather1DaoConfig.clearIdentityScope();
        weather2DaoConfig.clearIdentityScope();
        weather3DaoConfig.clearIdentityScope();
        weather4DaoConfig.clearIdentityScope();
        weather5DaoConfig.clearIdentityScope();
        cityDaoConfig.clearIdentityScope();
    }

    public Weather1Dao getWeather1Dao() {
        return weather1Dao;
    }

    public Weather2Dao getWeather2Dao() {
        return weather2Dao;
    }

    public Weather3Dao getWeather3Dao() {
        return weather3Dao;
    }

    public Weather4Dao getWeather4Dao() {
        return weather4Dao;
    }

    public Weather5Dao getWeather5Dao() {
        return weather5Dao;
    }

    public CityDao getCityDao() {
        return cityDao;
    }

}
